from .main import router as main_router
from .admin import router as admin_router
from .machine import router as machine_router
from .machine import routerAdmin as machine_admin_router
from .job import router as job_router
from .jobCategory import router as jobCategory_router
from .checkpointMethod import router as checkpointMethod_router
from .record import router as record_router
from .subdivisionA import router as subdivisionA_router
from .subdivisionB import router as subdivisionB_router
from .subdivisionC import router as subdivisionC_router
from .subdivisionSpecial import router as subdivisionSpecial_router
